import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { describe, expect, it } from "vitest";
import { z } from "zod";

import { canonicalItemSchema, thinPlanSchema } from "../domain/schemas";
import type { CanonicalItem } from "../domain/types";

/**
 * Guards the committed batch fixtures (regenerated by `npm run regen:samples`): the menu and
 * plan must validate, every plan item id must resolve to a real menu item, and every
 * image-slot item must actually have a photo — so the batch can never ship a blank carousel
 * slide or a binding that points at nothing. Pure data; no engine, network, or browser.
 */
const root = resolve(process.cwd(), "samples");
const menu = z
  .array(canonicalItemSchema)
  .parse(JSON.parse(readFileSync(resolve(root, "menu.json"), "utf8"))) as CanonicalItem[];
const plan = thinPlanSchema.parse(JSON.parse(readFileSync(resolve(root, "plan.json"), "utf8")));

describe("samples (batch fixtures)", () => {
  const byId = new Map(menu.map((i) => [i.id, i]));

  it("menu validates and uses full UUID ids", () => {
    expect(menu.length).toBeGreaterThan(0);
    for (const item of menu) expect(item.id.length).toBe(36);
  });

  it("every plan section item resolves to a real menu item", () => {
    for (const screen of plan.screens)
      for (const section of screen.sections)
        for (const id of section.items) expect(byId.has(id)).toBe(true);
  });

  it("every image-slot item exists and actually has a photo (no blank slides)", () => {
    for (const screen of plan.screens)
      for (const id of screen.imageSlot?.items ?? []) {
        const item = byId.get(id);
        expect(item, `imageSlot item ${id} missing from menu`).toBeDefined();
        expect((item?.images?.length ?? 0) > 0, `imageSlot item ${id} has no photo`).toBe(true);
      }
  });

  it("image-slot categoryId, when set, matches a real menu category", () => {
    const categories = new Set(menu.map((i) => i.category).filter(Boolean));
    for (const screen of plan.screens) {
      const cat = screen.imageSlot?.categoryId;
      if (cat !== undefined) expect(categories.has(cat)).toBe(true);
    }
  });
});
