/**
 * Regenerates `src/adapters/tailwind/motion-bundle.generated.ts` — the vanilla motion.dev
 * (motion/mini) animation core, bundled to a single self-contained IIFE and committed as a
 * string so the packager can inline it offline (the D14 runtime seam). Run via
 * `npm run build:motion` (and automatically by `prebuild`).
 *
 * Hard preconditions enforced here (fail loudly): the bundled lib must be fully self-contained
 * (no import/require/external url) AND must contain none of the engine's BAKED_PLAYER tokens
 * (window.location / history.pushState / window.open / location.href|assign|replace) — else
 * the inline runtime would trip the §5.1 self-contained QA gate and every board would fail.
 */
import { createRequire } from "node:module";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

import { build } from "esbuild";

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");
const outPath = resolve(repoRoot, "src/adapters/tailwind/motion-bundle.generated.ts");
const motionVersion = require("motion/package.json").version as string;

const ENTRY = `import { animate } from "motion/mini";\nglobalThis.__ceMotion = { animate };\n`;

const BAKED_PLAYER = [
  /\blocation\.(href|assign|replace)\b/,
  /\bwindow\.location\b/,
  /\bhistory\.(push|replace)State\b/,
  /\bwindow\.open\s*\(/,
];

async function main(): Promise<void> {
  const result = await build({
    stdin: { contents: ENTRY, resolveDir: repoRoot, loader: "js", sourcefile: "motion-entry.js" },
    bundle: true,
    minify: true,
    format: "iife",
    platform: "browser",
    write: false,
    legalComments: "none",
  });
  const code = result.outputFiles[0]?.text ?? "";

  // --- offline-safety + gate preconditions -------------------------------------------------
  const fail = (msg: string): never => {
    throw new Error(`build-motion-bundle: ${msg}`);
  };
  if (!code.includes("__ceMotion")) fail("bundle does not define __ceMotion");
  if (/\bimport\s*[({]/.test(code)) fail("bundle still contains an import (not self-contained)");
  if (/\brequire\s*\(/.test(code)) fail("bundle still contains require() (not self-contained)");
  if (/\burl\(/i.test(code)) fail("bundle contains a css url() (potential external ref)");
  if (/https?:\/\//.test(code)) fail("bundle contains an http(s) URL (external ref)");
  for (const re of BAKED_PLAYER) {
    const m = code.match(re);
    if (m)
      fail(`bundle contains a BAKED_PLAYER token "${m[0]}" — would trip the self-contained gate`);
  }

  const banner =
    `/* AUTO-GENERATED by scripts/build-motion-bundle.ts — DO NOT EDIT.\n` +
    `   Vanilla motion.dev (motion/mini) v${motionVersion}, bundled to a self-contained IIFE\n` +
    `   that sets globalThis.__ceMotion = { animate }. Regenerate with \`npm run build:motion\`. */\n`;
  const file = `${banner}export const MOTION_LIB = ${JSON.stringify(code)};\n`;
  writeFileSync(outPath, file, "utf8");

  console.warn(
    `build-motion-bundle: wrote ${outPath} (${code.length} chars, motion@${motionVersion}) — gate-clean.`,
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
